# Uncomment the next line to define a global platform for your project
 platform :ios, '14.0'

target 'PDF' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PDF
	pod 'MBProgressHUD'
	pod 'SnapKit'
	pod 'SQLite.swift'
	pod 'MJRefresh'

	pod 'ZLPhotoBrowser'
  	pod 'SwiftyStoreKit'
  	pod 'SwiftyJSON'
  	#pod 'FirebaseAnalytics'
  	pod 'Google-Mobile-Ads-SDK'
#    pod 'SwiftOCR'
    pod 'DocX-Swift'
    pod 'SwiftXLSX'
    pod 'SignatureView'

end
